spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  kafka:
    bootstrap-servers: helppoint-kafka:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://helppoint-discovery-server:8761/eureka/

kafka:
  bootstrapAddress: helppoint-kafka:9092