spring:
  zipkin:
    baseUrl: http://localhost:9411/

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrapAddress: localhost:9092